# Generated by Django 3.2 on 2025-11-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('premium', 'Premium'), ('offroad', 'Offroad'), ('normal', 'Normal')], default='normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
