# Generated by Django 3.2 on 2025-11-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20251113_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('premium', 'Premium'), ('offroad', 'Offroad')], max_length=50),
        ),
    ]
