# Generated by Django 3.2 on 2025-11-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_car_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('premium', 'Premium'), ('offroad', 'Offroad')], max_length=20),
        ),
    ]
