# Generated by Django 6.0 on 2025-12-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
