# Generated by Django 6.0 on 2025-12-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_phoneotp_rename_register_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneotp',
            name='is_verified',
        ),
    ]
