# Generated by Django 6.0 on 2025-12-29 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_remove_phoneotp_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneotp',
            old_name='phone_number',
            new_name='phonenumber',
        ),
    ]
