# Generated by Django 6.0 on 2025-12-29 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_rename_phone_number_phoneotp_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='category',
        ),
        migrations.AddField(
            model_name='car',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('luxury', 'Luxury')], default='sedan', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 29, 11, 36, 30, 601746, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG'), ('electric', 'Electric')], default='petrol', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default='2020', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='place',
            field=models.CharField(default='kottayam', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.PositiveIntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Manual', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='variant',
            field=models.CharField(default='top', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='price_per_day',
            field=models.PositiveIntegerField(),
        ),
    ]
