# Generated by Django 6.0 on 2026-01-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_remove_booking_from_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='drop_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='drop_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='drop_datetime',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_datetime',
            field=models.CharField(default='', max_length=100),
        ),
    ]
