# Generated by Django 6.0 on 2026-01-23 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_remove_booking_drop_date_remove_booking_drop_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.user'),
            preserve_default=False,
        ),
    ]
