# Generated by Django 6.0 on 2026-01-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_booking_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='drop_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_datetime',
            field=models.DateTimeField(),
        ),
    ]
