# Generated by Django 6.0 on 2026-01-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_alter_booking_drop_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='CANCELLED', max_length=20),
        ),
    ]
