# Generated by Django 6.0 on 2026-01-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='BOOKED', max_length=20),
        ),
    ]
