# Generated by Django 6.0 on 2026-01-24 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_alter_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='price_per_day',
            new_name='price_per_hour',
        ),
    ]
