# Generated by Django 6.0 on 2026-01-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_owner_ownerotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
