# Generated by Django 6.0 on 2026-01-26 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_owner_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='userid',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='members.owner'),
            preserve_default=False,
        ),
    ]
