# Generated by Django 6.0 on 2026-01-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_car_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='userid',
            new_name='ownerid',
        ),
    ]
