# Generated by Django 6.0 on 2026-01-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_booking_ownerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='ownerid',
            new_name='owner_id',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='ownerid',
            new_name='owner_id',
        ),
    ]
