# Generated by Django 6.0 on 2026-01-26 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_rename_ownerid_booking_owner_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='userid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
