# Generated by Django 6.0 on 2026-02-03 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_booking_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.user')),
            ],
            options={
                'unique_together': {('user', 'car')},
            },
        ),
    ]
