# Generated by Django 6.0 on 2026-02-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0033_review_booking_alter_review_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('running', 'Running'), ('ready_for_pickup', 'Ready for Pickup'), ('maintenance', 'Maintenance')], default='Available', max_length=50),
        ),
    ]
