# Generated by Django 6.0 on 2026-03-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0034_car_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='landmark',
            field=models.CharField(default='Near Railway Station', max_length=150),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('running', 'Running'), ('maintenance', 'Maintenance')], default='Available', max_length=50),
        ),
    ]
