# Generated by Django 6.0 on 2026-03-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0035_car_landmark_alter_car_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('password', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('offline', 'Offline')], default='offline', max_length=20)),
            ],
        ),
    ]
