# Generated by Django 6.0 on 2026-03-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0037_booking_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='want_driver',
            field=models.BooleanField(default=False),
        ),
    ]
